name: Release Pipeline

on: 
  push:
    branches:
      - master

jobs:

  prod-deploy:
    name: prod-deploy
    environment: prod
    runs-on: ubuntu-latest
    # This line ensures the deploy step is only run on pushes to master
    if: github.ref == 'refs/heads/master'
    steps:
      - name: "[STEP] Checkout"
        uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      
      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Add Heroku CLI to PATH
        run: |
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: "[STEP] Deploy to Heroku"
        uses: akhileshns/heroku-deploy@v3.14.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: the-penny-press
          heroku_email: sean.travis.taylor@gmail.com
        env: 
          HD_DATABASE_URL: ${{secrets.DATABASE_URL}}
          HD_SUPABASE_SERVICE_ROLE: ${{secrets.SUPABASE_SERVICE_ROLE}}
